import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import '@/styles/globals.css';
import StoreProvider from '@/lib/Provider/StoreProvider';
import Navigation from '@/common/components/Navigation';

const ubuntu = Ubuntu({
  subsets: ['latin'],
  style: ['normal'],
  weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'FRONTEND EXAM - FAISHAL HANIF',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={ubuntu.className}>
          <Navigation />
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
